name: Release Labellerr MCP Server

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: |
        node test-functionality.js
        node validate-integration.js
      env:
        LABELLERR_API_KEY: test_key
        LABELLERR_API_SECRET: test_secret
        LABELLERR_CLIENT_ID: test_client

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Labellerr MCP Server ${{ github.ref }}
          
          ### Features
          - 22 tools across 5 categories
          - Complete Labellerr SDK integration
          - Real-time monitoring and analytics
          - Natural language interface via Claude Desktop
          - Comprehensive error handling
          
          ### Installation
          ```bash
          git clone https://github.com/${{ github.repository }}
          cd labellerr-mcp-server
          npm install
          cp .env.example .env
          # Edit .env with your Labellerr credentials
          ```
          
          ### Usage
          See README.md for complete documentation and examples.
        draft: false
        prerelease: false
